[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flexcpi"
version = "0.1.0"
description = "A customizable CPI basket tool for empirical inflation measurements using BLS data."
readme = "README.md"
authors = [
    { name = "Rory G. Quinlan" }
]
license = {text = "MIT"}
keywords = [
    "consumer price index",
    "price index construction",
    "inflation measurement",
    "empirical economics",
    "economic measurement tools",
    "cost-of-living analysis",
    "macroeconomic modeling",
    "BLS data integration",
    "economic statistics pipeline"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Economics"
]
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "requests",
    "openpyxl"  # For loading downloaded Excel BLS weights
]

[project.urls]
Homepage = "https://github.com/RoryQo/FlexCPI"
Repository = "https://github.com/RoryQo/FlexCPI"
Issues = "https://github.com/RoryQo/FlexCPI/issues"
