[project]
name = "flexcpi"
version = "0.1.0"
description = "Build and analyze custom CPI baskets using BLS data"
authors = [{name = "Rory G Quinlan"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pandas", "matplotlib", "requests"]

[tool.setuptools.package-data]
"flexcpi.data" = ["*.csv", "*.txt"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
